#!/bin/bash
echo 'this is download_bashrc'
cp ~/.bashrc ./
echo '以下是 本地版本 和 master版本 的差别'
git diff .bashrc
echo ''
echo '提示：红色为master版本；绿色为本地版本'
echo '下载yes<->退出no'
YES="yes"
read SELECT

if [ $SELECT = $YES ]
then
    git checkout .bashrc
    cp .bashrc ~/.bashrc
else
	echo '退出'
fi
